X = [
    # 3 letters
    'xis',
    # 4 letters
    'xyst',
    # 5 letters
    'xebec',
    'xenia',
    'xenic',
    'xenon',
    'xeric',
    'xerox',
    'xerus',
    'xylan',
    'xylem',
    'xylol',
    'xylyl',
    'xysti',
    'xysts',
    # 6 letters
    'xebecs',
    'xenial',
    'xenias',
    'xenons',
    'xylans',
    'xylems',
    'xylene',
    'xyloid',
    'xylols',
    'xylose',
    'xylyls',
    'xyster',
    'xystoi',
    'xystos',
    'xystus',
    # 7 letters
    'xanthan',
    'xanthic',
    'xanthin',
    'xenopus',
    'xerarch',
    'xeroses',
    'xerosis',
    'xerotic',
    'xeroxed',
    'xeroxes',
    'xeruses',
    'xiphoid',
    'xylenes',
    'xylidin',
    'xylitol',
    'xyloses',
    'xysters',
    # 8 letters
    'xanthans',
    'xanthate',
    'xanthein',
    'xanthene',
    'xanthine',
    'xanthins',
    'xanthoma',
    'xanthone',
    'xanthous',
    'xenogamy',
    'xenogeny',
    'xenolith',
    'xenotime',
    'xerosere',
    'xeroxing',
    'xiphoids',
    'xylidine',
    'xylidins',
    'xylitols',
    'xylocarp',
    'xylotomy',
]